version: '3'

services:

  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./docker/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: Fibonacci
  
  nextjs:
    ports:
      - 5000:5000
    build:
      context: ./packages/next
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  
  jobs:
    build:
      context: ./packages/jobs
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_DATABASE=fibonacci
      - DB_USER=postgres
      - DB_PASSWORD=Fibonacci
      - DB_PORT=5432